kaltura/player-studio

- app/view/list.html
Correct usage of the words Update and Upgrade to indicate:
Upgrade -> V1 to V2
Update -> V2 to latest V2
For reference see the difference explained for usage of these terms by Apple: https://support.apple.com/en-am/HT201564
> Correct usage of the words Update and Upgrade

- app/js/controllers/EditCtrl.js
- app/js/services/services.js
using https://github.com/kaltura/server/pull/7133
> feat: support freeze latest and beta for plugins version

- app/js/controllers/playerListCtrl.js
evaluate OVP/OTT based on the duplicated confvars
> fix(FEC-8385): duplicate OTT player saved as OVP player

- app/js/services/v3Properties.json
> feat(FEC-8479): add flash checkbox

- app/js/services/v3Properties.json
add support for toggling youtube bundle on/off
> feat(FEC-8880): add support for youtube

- app/js/controllers/EditCtrl.js
- app/js/controllers/playerListCtrl.js
This reverts commit 9bd61d4 because with this change it not needed any more .
> fix(FEC-8894, FEC-8895): OVP player identified as OTT and vice versa

- app/js/services/v3Properties.json
set `resetKalturaPlayer:true` for flash and youtube
> fix(FEC-8902): support YouTube playback not working after preview changes

- app/js/controllers/EditCtrl.js
- app/js/services/defaultPlayer.json
- app/js/services/services.js
- app/js/services/v3Properties.json
add ui.component to default config and defaultive check for uiConfig which created before.
add new section for look and feel as was in V2 for ui configuration.
> feat: add look and feel section

- app/js/controllers/EditCtrl.js
- app/js/services/v3Properties.json
- app/less/app.less
- app/templates/category.html
* Don't show checkbox for the translation selection and open it by default
* Description and helpnotes
* Fix dropdown items boundaries for the KMC studio
> fix(FEC-9653): if check localization checkbox, its doesn't saved after reopen Look and Feel category

- app/js/services/v3Properties.json
> feat(FEC-9621): add all default language

- app/js/controllers/EditCtrl.js
> fix(10020): if some language duplicated in uiconf, in studio default language list will be empty

- app/js/controllers/EditCtrl.js
- app/js/services/v3Properties.json
added new plugin configuration to support new floating player feature under "Look and feel" category
Solves FEC-9972
> feat(FEC-9972): floating player

- app/js/controllers/EditCtrl.js
- app/js/directives.js
- app/js/services/v3Properties.json
Added IMA-DAI to studio configuration
Also updated the IMA google SDK link as it was not valid
Solves FEC-9732
> feat(FEC-9732): DFP DAI - Studio Configuration

- app/js/services/v3Properties.json
> feat(FEC-10105): As a platform user I would like to be able to toggle floating player re-positioning capability on and off

- app/js/controllers/EditCtrl.js
- app/js/services/services.js
- app/js/services/v3Properties.json
Removed completely the use of 'removeUnsupportedPlugins'
Tested successfully - also with other plugins
solves FEC-10283
> feat(FEC-10283): add arbitrary studio config in advanced menu

- app/js/controllers/EditCtrl.js
add analytics plugins for player >= 0.56.0
> feat(FEC-10401): add analytics plugins in studio

- app/js/controllers/EditCtrl.js
- app/js/services/defaultPlayer.json
- app/js/services/v3Properties.json
Solves [FEC-10868](https://kaltura.atlassian.net/browse/FEC-10868) and [FEC-10550](https://kaltura.atlassian.net/browse/FEC-10550)
> feat(FEC-10868): Timeline Scrubber Studio Configuration

- app/js/controllers/EditCtrl.js
- app/js/services/v3Properties.json
This flag is not enough customer have to set the ad holiday duration on stream DFP configuration.
> feat(FEC-10581): add option to enable preroll for IMA DAI

- app/js/controllers/EditCtrl.js
> feat(FEC-10606): add a warning when trying to update configuration for a version "frozen" player

- app/js/services/services.js
distinguish between old players and news
> fix(FEC-11384): studio is crashing on null pointer

- Gruntfile.js
- app/js/controllers/relatedCtrl.js
- app/js/services/v3Properties.json
- package-lock.json
- package.json
Add Related-Plugin configuration to the V3-Studio
And add backward compatibility support for ES6 syntax on the bundle building process 
solves: FEC-11590
> feat(FEC-11590): Related grid Studio requirements

- app/js/services/v3Properties.json
Add Skip Plugin to V3 Studio
solves: FEC-12028
> fix(FEC-12028): Skip Plugin - Studio

- app/js/services/v3Properties.json
> feat(FEC-12116): CC button for on/off subtitles

- app/js/controllers/playerListCtrl.js
- app/js/services/services.js
Fixed controllers order to be working in minified build.
> fix(ILMS-391): Nothing happens after pressing the convert button.
